### ISSUE TITLE
Cannot remove hashbangs

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vue-hackernews#13]
I've tried numerous solutions to remove the hashbang (`#!`) or hash (`#`) from the URL, but the app always breaks when it comes to links. Set `history: true` - all links are prefixed with`#` as in `Item.vue` however we can't match that route and if we remove the hash, the app will break. I also set `<base href="/">` in the `<head>` of `index.html`. Please advise.

**Comment by yyx990803** [comment]
This is simply because I'm not using `v-link`. See http://router.vuejs.org/en/link.html

**Comment by niallobrien** [comment]
Thank you.
