### ISSUE TITLE
babel-runtime@^5.8.0 is needed

### ISSUE THREAD

**Issue by dongli** [vuejs/vue-hackernews#18]
I am new to VueJS, and I cloned this repo. Just want to repeat the process, but I meet this WARN:

```
$ npm install
npm WARN EPEERINVALID vue-loader@7.2.0 requires a peer of babel-runtime@^5.8.0 but none was installed.
```

**Comment by yyx990803** [comment]
fixed.

**Comment by Fezilk** [comment]
No, problem is still

**Comment by anke1460** [comment]
我也遇到这样的问题
npm WARN EPEERINVALID vue-loader@7.5.3 requires a peer of babel-runtime@^5.8.0 but none was installed.
npm ERR! code 1

**Comment by decebal** [comment]
+1
