### ISSUE TITLE
Should babel-runtime and babel-plugin-transform-runtime be in dependencies?

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue-hackernews#24]
In package.json, I think dependencies should contain run time dependencies, and devDependencies should contain compile time dependencies. Literally, babel-runtime and babel-plugin-transform-runtime mean plugins supporting run time things. So shouldn't they be in dependencies?

**Comment by yyx990803** [comment]
App code never directly require babel-runtime, so it's invisible to actual source code. I would only put things that I directly import in source code as dependency.
