### ISSUE TITLE
Need babel-runtime but the the version is not the latest

### ISSUE THREAD

**Issue by snowffer** [vuejs/vue-hackernews#26]
When I install babel-runtime, the latest version is 6.3.19. Then I install vue-loader, there is an warning:

`vue-loader@8.0.2 requires a peer of babel-runtime@^5.8.0 but none was installed.`

It seems that version 5.8.0 is needed here. So my question is, if I install 6.3.19, could that block my project?

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-loader/issues/96#issuecomment-162910917
