### ISSUE TITLE
ERROR in Cannot find module '../urls/rewrite'

### ISSUE THREAD

**Issue by johnsuna** [vuejs/vue-hackernews#37]
win7_64: npm run dev
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/NewsView.vue
Module build failed: TypeError: F:\hacknews\src\components\NewsView.vue:102:1
......
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/App.vue
Module build failed: TypeError: F:\hacknews\src\components\App.vue:93:1
......
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stys-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/Coent.vue
Module build failed: TypeError: F:\hacknews\src\components\Comment.vue:67:1

**Comment by La-toile-cosmique** [comment]
I had the same issue using node v6.0.0 on Ubuntu 64.
Using v5.6.0 solved the problem on my machine.

**Comment by johnsuna** [comment]
@La-toile-cosmique Thank you!
