### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by yuxiaoxia** [vuejs/vue-hackernews#40]
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/stylus-loader!./~/vue-loader/lib/selecto              r.js?type=style&index=0!./src/components/NewsView.vue
Module build failed: TypeError: E:\test\vue\vue-hackernews\src\components\NewsView.vue:102:1
    98|     a
    99|       margin-right 10px
   100|       &:hover
   101|         text-decoration underline
   102|
--------^
安装的时候报了好多css的错误，我是少了什么吗？可是你们也没说明

**Comment by daiweixiong** [comment]
我也是报了很多类似的错误，没找到原因，请大神解答下

**Comment by yyx990803** [comment]
依赖旧了，stylus-loader 更新到最新的就好了。
