### ISSUE TITLE
没有build.js,也能运行，为什么

### ISSUE THREAD

**Issue by daiweixiong** [vuejs/vue-hackernews#41]
把./static里的build.js删掉，不运行npm run build这个命令。http://localhost:8080也能运行正常。请问这是为什么，index.html里的<script src="static/build.js"></script>这个为什么没报错？
请大神解惑释疑，不甚感激。

**Comment by yyx990803** [comment]
因为开发时用的是 dev-server，直接从内存 serve 的。
